fix(tools): make deploy-all able to take existing addrs (#318)
Plus some minor refactoring to pull out the common code into functions
so it's easier to see the main flow. And a bit of output formatting to
break it up a bit so it's no so blinding.

Also fixes a bug with deploying SignatureVerificationLib needing a path
prefix.

---

I tackled this because SignatureVerificationLib was broken and it
wouldn't deploy. And then I didn't want to sit through all of the other
contracts deploying again so now it takes existing contracts, I can do:

```
SESSION_KEY_REGISTRY_ADDRESS=0xc466FB7E6eb15FBD3212F24e29e1F7b30026508D \
VERIFIER_IMPLEMENTATION_ADDRESS=0x3F70afc1DEDC0Bd3D01eF92A1bE298bA194F2E7e \
PDP_VERIFIER_ADDRESS=0x59061BAbF95754DfB7aade185D428B63DC1250a4 \
PAYMENTS_CONTRACT_ADDRESS=0x5C37908759aF37A1708857c29C32AfA805c86dD3 \
REGISTRY_IMPLEMENTATION_ADDRESS=0xAD241261b5831e2Da6f46f199881039fF516218f \
SERVICE_PROVIDER_REGISTRY_PROXY_ADDRESS=0x688002Ccd0cfC8E5480DCEDfd52710D9407b45D3 \
SIGNATURE_VERIFICATION_LIB_ADDRESS=0x43Fc46269ba3eec42D4dCf5f6F3888686EA8e02c \
DRY_RUN=false \
ETH_RPC_URL=https://api.calibration.node.glif.io/rpc/v1 \
ETH_KEYSTORE=~/.foundry/keystores/calibnet_synapse \
CHALLENGE_FINALITY=10 \
MAX_PROVING_PERIOD=60 \
SERVICE_NAME='My test contract' \
SERVICE_DESCRIPTION="Test deployment, don't use this" \
./tools/deploy-all-warm-storage.sh
```

and it's much quicker the second time around.

But I still have problems with verification at the end, unrelated but
probably important:

```
⠸ Verifying contract on Filfox...

Verification Result:
✖ ⚠️  Compilation error in source files.
✖ 📝 Details: ParserError: Source "lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol" not found: File import callback not supported
 --> @pdp/PDPVerifier.sol:9:1:
  |
9 | import {Initializable} from "../lib/openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Filfox verification successful for PDPVerifier
```

Same thing for MyERC1967Proxy, FilecoinPayV1, ERC1967Proxy,
FilecoinWarmStorageService, etc.. just keeps going

Doesn't seem fatal though?